apiVersion: v1
kind: Service
metadata:
  name: sensor-ingestion
  labels:
    app: identity-api
spec:
  selector:
    app: sensor-ingestion
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
